trigger:
    -main

pool:
  name: MySelfHostedPool

stages:
  - stage: build
  displayname: Build and Print
  jobs:
  - job:: PrintHello
   displayName: Print Hello World
   steps:
   - checkout: self
   -script: 
        chmod +x ./helloworld.sh
        ./helloworld.sh
        displayname: 'Run Print_helloworld.sh'
